# Generated by Django 2.0.5 on 2018-05-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chromosome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.TextField()),
                ('is_circular', models.IntegerField(default=0)),
                ('trunc512', models.TextField()),
                ('md5', models.TextField()),
                ('size', models.IntegerField()),
            ],
        ),
    ]
