# Generated by Django 2.0.5 on 2018-05-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chromosome',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
